import sys
from snakemake.utils import min_version

###### minimum snakemake version ######
min_version("7.0")

###### load rules ######
include: "rules/pipeline.smk"
include: "rules/test.smk"

###### target rules ######
rule all:
    input:
        get_pipeline_output()